// <auto-generated />
namespace ResponsiveGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnametotags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnametotags));
        
        string IMigrationMetadata.Id
        {
            get { return "201608272145445_add name to tags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
